base_link: base_link

main_eef:
  end_effector_name : 'main_eef'

  # Default grasp params
  joints: ['gripper_joint', 'gripper2_joint']

  pregrasp_posture :          [0.0, 0.0]
  pregrasp_time_from_start :  4.0

  grasp_posture :             [1.0, 1.0]
  grasp_time_from_start :    4.0
  #grasp_time_from_start :     *time_from_start

  #postplace_time_from_start : *time_from_start

  # Desired pose from end effector to grasp [x, y, z] + [R, P, Y]
  grasp_pose_to_eef :          [0.0, 0.0, 0.0]
  grasp_pose_to_eef_rotation : [0.0, 0.0, 0.0]

  end_effector_parent_link : arm_wrist_flex_link
