controller_list:
  - name: turtlebot/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_shoulder_pan_joint
      - arm_bicep_joint
      - arm_forearm_joint
      - arm_wrist_flex_joint
      - gripper_link_joint
#  - name: turtlebot/gripper_controller
#    action_ns: follow_joint_trajectory  #gripper_action 
#    type: FollowJointTrajectory #GripperCommand FollowJointTrajectory 
#    default: true
#    joints:
#      - gripper_joint
#      - gripper2_joint

#version GripperCommand
  - name: turtlebot/gripper_controller
    action_ns: gripper_cmd  #follow_joint_trajectory  
    type: GripperCommand # FollowJointTrajectory 
    default: true
    command_joint: gripper_joint
    joints:
      - gripper_joint
#      - gripper2_joint
